name: CI

on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      SDL_VIDEODRIVER: dummy
      PYTHONUNBUFFERED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install system deps (SDL)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame-ce
          pip install -r requirements.txt || true

      - name: Run tests
        run: |
          pytest -q

      - name: Upload test results (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-failures
          path: .
